# NOTE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#   █████  ████████ ██    ██ ██ ███    ██
#  ██   ██    ██    ██    ██ ██ ████   ██
#  ███████    ██    ██    ██ ██ ██ ██  ██
#  ██   ██    ██    ██    ██ ██ ██  ██ ██
#  ██   ██    ██     ██████  ██ ██   ████
#
#  Author       : zx0r
#  License      : MIT License
#  Description  : Stay hungry; Stay foolish
#  Contact Info : https://github.com/zx0r/hyprdots-gentoo

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

## where to store your database, default is your system data directory
## linux/mac: ~/.local/share/atuin/history.db
## windows: %USERPROFILE%/.local/share/atuin/history.db
db_path = "$HOME/.local/share/atuin/history.db"

## where to store your encryption key, default is your system data directory
## linux/mac: ~/.local/share/atuin/key
## windows: %USERPROFILE%/.local/share/atuin/key
key_path = "$HOME/.local/share/atuin/key"

## where to store your auth session token, default is your system data directory
## linux/mac: ~/.local/share/atuin/session
## windows: %USERPROFILE%/.local/share/atuin/session
sesision_path = "$HOME/.local/share/atuin/session"

## address of the sync server
sync_address = "https://api.atuin.sh"

## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checks
update_check = true

## how often to sync history. note that this is only triggered when a command
## is ran, so sync intervals may well be longer
## set it to 0 to sync after every command
sync_frequency = "10m"

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
search_mode = "fuzzy"

## which filter mode to use
## possible values: global, host, session, directory
filter_mode = "global"

## With workspace filtering enabled, Atuin will filter for commands executed
## in any directory within a git repository tree (default: false)
workspaces = false

## which filter mode to use when atuin is invoked from a shell up-key binding
## the accepted values are identical to those of "filter_mode"
## leave unspecified to use same mode set in "filter_mode"
filter_mode_shell_up_key_binding = "global"

## which search mode to use when atuin is invoked from a shell up-key binding
## the accepted values are identical to those of "search_mode"
## leave unspecified to use same mode set in "search_mode"
search_mode_shell_up_key_binding = "fuzzy"

## which style to use
## possible values: auto, full, compact
style = "auto"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 0

## Invert the UI - put the search bar at the top , Default to `false`
invert = false

## enable or disable showing a preview of the selected command
## useful when the command is longer than the terminal width and is cut off
show_preview = true

## Configure the maximum height of the preview to show.:%s
## Useful when you have long scripts in your history that you want to distinguish
## by more than the first few lines.
max_preview_height = 4

## Configure whether or not to show the help row, which includes the current Atuin
## version (and whether an update is available), a keymap hint, and the total 
## amount of commands in your history.
show_tabs = true

## Configure whether or not to show the help row, which includes the current Atuin
## version (and whether an update is available), a keymap hint, and the total
## amount of commands in your history.
show_help = true

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
#exit_mode = "return-query"
exit_mode = "return-original"

## Configures whether to store commands that failed (those with non-zero exit status) or not.
store_failed = true

## possible values: emacs, subl
word_jump_mode = "emacs"

## The terminal’s cursor style associated with each keymap mode in the Atuin search. 
## This is specified by a dictionary whose keys and values being the keymap names and 
## the cursor styles, respectively. A key specifies one of the keymaps from emacs, 
## vim_insert, and vim_normal. A value is one of the cursor styles,
## default or {blink,steady}-{block,underline,bar}. The following is an example.
keymap_cursor = { emacs = "blink-underline", vim_insert = "blink-underline", vim_normal = "steady-block" }

## characters that count as a part of a word
# word_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## number of context lines to show when scrolling by pages
# scroll_context_lines = 1

## The history format allows you to configure the default history list format - which can also 
## be specified with the —format arg.
## The specified —format arg will prioritize the config when both are present
## More on https://docs.atuin.sh/reference/list/
history_format = "history_filter"

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
# history_filter = [
#   "^secret-cmd",
#   "^innocuous-cmd .*--secret=.+"
# ]

## prevent commands run with cwd matching any of these regexes from being written
## to history. Note that these regular expressions are unanchored, i.e. if they don't
## start with ^ or end with $, they'll match anywhere in CWD.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
# cwd_filter = [
#   "^/very/secret/area"
# ]


## use ctrl instead of alt as the shortcut modifier key for numerical UI shortcuts
## alt-0 .. alt-9
# ctrl_n_shortcuts = false

## Defaults to true. This matches history against a set of default regex, and will not save it if we get a match. Defaults include
## 1. AWS key id
## 2. Github pat (old and new)
## 3. Slack oauth tokens (bot, user)
## 4. Slack webhooks
## 5. Stripe live/test keys
secrets_filter = true

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = true

# Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo"]

[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "cd",
  "cargo",
  "composer",
  "dnf",
  "duf",
  "dooit",
  "doas",
  "eix",
  "emerge",
  "docker",
  "git",
  "go",
  "ip",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "python",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]

# [theme]
name = ""
debug = false
parent = "autumn"
max_depth = 10

[colors]
AlertInfo = "#00ff00"       # Bright green for informational messages
AlertWarn = "#ffcc00"       # Yellow to capture attention for warnings
AlertError = "#ff0033"      # Red for critical errors needing immediate action
Annotation = "#888888"      # Gray for supporting text, unobtrusive but readable
Base = "#ffffff"            # Default foreground color (white for readability)
Guidance = "#888844"        # Muted yellow-green for instructive text
Important = "#ff6600"       # Orange for high-priority information
Title = "#ff66ff"           # Vibrant pink for headings to match the cyberpunk theme

[sync]
records = true

[dotfiles]
enabled = true

## This section of the client config is specifically for configuring key-related settings.
[keys]
scroll_exits = true
prefix = 'a'

## This section of the client config is specifically for configuring preview-related settings. 
## (In the future the other 2 preview settings will be moved here.)
[preview]
strategy = "auto"

## Enable the background daemon
## Add the new section to the bottom of your config file
[daemon]
enabled = false
tcp_port = 8889
sync_frequency = 300
systemd_socket = false
socket_path = "$HOME/.local/share/atuin/atuin.sock"
# socket_path = "/run/user/1000/atuin.sock"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

